public_html/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
});


Route::get('/videos',function(){
	$get_all_videos = App\Video::orderBy('id','desc')->get();
	return view('front_end.videos')->with('get_all_videos',$get_all_videos);
});


Route::get('/', function () {
    return view('index');
});

Route::get('/register',function(){
	abort(404);
});

Route::get('/company_projects','ProjectContoller@companyProjects');
//Route::get('/company_projects/{id}','ProjectContoller@companyProjectDetail');


Route::get('/company_documents/{id}','DocumentController@getOneDocument');

Route::get('/about_us','FrontEndController@aboutUs');
Route::get('/contact_us','FrontEndController@contactUs');
Route::post('/send_message_contact_us','FrontEndController@sendMessageContactUs');
Route::get('logout', 'Auth\LoginController@logout');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('forget_password', function()
{   if (Route::has('login')) {
        if (Auth::check()) {
            return redirect('/login');
    
}
return view('front_end.forget_password'); 
}
});
	
Route::get('/company_documents','DocumentController@allDocumentsFrontEnd');

Route::get('/photos','FrontEndController@allPhotos');
Route::get('album','FrontEndController@allAlbums');
Route::get('album/{id}','FrontEndController@photoAlbum');
Route::get('/google74b7c7d77aa0b104.html',function(){

return view('google_file');
});

Route::group(['middleware' => ['auth']], function () {
Route::get('/contact_us_messages','BackEndController@getContactUsMessages');    
Route::post('/set_message_read','BackEndController@markMessageRead');
Route::get('/create_user','UserController@createUser');
Route::get('/all_users','UserController@viewUsers');
Route::post('/add_user','UserController@addUser');
Route::get('edit_user/{id}','UserController@editUser');
Route::post('/update_user','UserController@updateUser');
Route::post('/delete_contact_message','BackEndController@deleteContactMessage');
Route::get('/undo_contact_message_delete/{id}','BackEndController@undoDeleteContactMessage');
Route::get('/create_slider_show','FrontEndController@createSliderShow');
Route::get('/all_slider_show','FrontEndController@getAllSliderShowImges');
Route::post('/upload_new_slider_show','FrontEndController@uploadNewSliderShow');
Route::post('/end_slide_show','FrontEndController@endSliderShow');
Route::post('/delete_slider_image','FrontEndController@deleteSliderImage');
Route::get('/undo_delete_slider/{id}','FrontEndController@undoDeleteSliderImage');
Route::get('/my_profile','ProfileController@myProfile');
Route::post('/upload_profile_photo','ProfileController@uploadProfilePhotos');
Route::post('/change_my_password','ProfileController@changePassword');
Route::get('/set_image_default/{id}','ProfileController@setImageDefault');
Route::get('/delete_profile_image/{id}','ProfileController@deleteProfileImage');
Route::get('/upload_video','VideoController@uploadVideo');
Route::post('/upload_new_video','VideoController@uploadNewVideo');
Route::get('/all_videos','VideoController@allVideos');
Route::post('/delete_video','VideoController@deleteVideo');
Route::get('/undo_delete_video/{id}','VideoController@undoDeleteVideo');
Route::get('/all_documents','DocumentController@allDocuments');
Route::get('/document/{id}','DocumentController@oneDocument');
Route::post('/add_document','DocumentController@addDocument');
Route::get('/create_document','DocumentController@createDocument');
//Route::get('/create_photo','PhotoController@createPhoto');
//Route::get('/all_photos','PhotoController@allPhotos');
Route::post('/add_photo','PhotoController@addPhoto');
Route::get('/delete_photo/{id}','PhotoController@deletePhoto');
Route::get('/undo_delete_photo/{id}','PhotoController@undoDeletePhoto');
Route::post('/change_my_name','ProfileController@changeName');
Route::get('/message/{id}','FrontEndController@getMessage');
Route::post('/upload_document_image','DocumentController@uploadDocumentImage');
Route::get('/delete_document_image/{id}','DocumentController@deleteDocumentImage');
Route::get('/undo_delete_document_image/{id}','DocumentController@undoDeleteDocumentPhoto');
Route::post('/edit_document_name','DocumentController@update');
Route::resource('projects','ProjectContoller');
Route::post('/upload_project_image','ProjectContoller@uploadImage');
Route::get('/delete_project_image/{id}','ProjectContoller@deleteProjectImage');
Route::get('/undo_delete_project_image/{id}','ProjectContoller@undoDeleteProjectImage');
Route::get('/active_user/{id}','UserController@Activation');
Route::post('/delete_documents','DocumentController@deleteDocuments');
Route::get('/undo_document_delete/{id}','DocumentController@undoDeleteDocument');
Route::get('/set_first_slider/{id}','FrontEndController@setSliderFirst');
Route::get('/projects/edit/{id}','ProjectContoller@editProject');
Route::post('/update_project','ProjectContoller@updateProject');
Route::get('/delete_project/{id}','ProjectContoller@deleteProject');
Route::get('/undo_delete_project/{id}','ProjectContoller@undoDeleteProject');
Route::resource('last_news','LastNewsController');
Route::post('/update_news','LastNewsController@updateNews');
Route::get('delete_news/{id}','LastNewsController@destroy');
Route::get('/undo_delete_news/{id}','LastNewsController@undoDeleteNews');
Route::get('/active_news/{id}','LastNewsController@activeNews');
Route::resource('albums','AlbumController');
Route::post('/update_album','AlbumController@updateAlbum');
Route::get('/active_album/{id}','AlbumController@activeAlbum');
Route::post('/change_album','AlbumController@changeAlbum');
Route::get('test_slider','DocumentController@testSlider');
});

public_html/app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Project extends Model
{
   
	use SoftDeletes;
   public function AddedBy()
    {
    	return $this->hasOne('App\User','id','added_by');
    }

    public function UpdatedBy()
     {
     	return $this->hasOne('App\User','id','updated_by');
     }

     public function DeletedBy()
      {
      	return $this->hasOne('App\User','id','deleted_by');
      } 
}

public_html/app/Http/Controllers/BackEndController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\contactMessage;
use Session;
use Auth;
use App\User;
use DB;
class BackEndController extends Controller
{
    public function getContactUsMessages()
    {
    	$get_all_messages = contactMessage::all();
    	return view('back_end.contact_us_messages')->with('get_all_messages',$get_all_messages);
    }

    public function markMessageRead(Request $request)
    {
    	$get_message = contactMessage::find($request->message_id);
    	if ($get_message) {
    		
    			
    		if ($get_message->read_or_not == 0) {
    			$get_message->read_or_not = 1 ;
    			$get_message->read_by = Auth::User()->id;
    			$get_message->save();
    			Session::flash('message_read','Message successfully read !');
    			return redirect()->back();		
    	}

    		elseif ($get_message->read_or_not == 1) {

    			$get_message->read_or_not = 0 ;
    			$get_message->read_by = 0;
    			$get_message->save();
    			Session::flash('message_read','Message successfully Not read !');
    			return redirect()->back();		
    		}	
    	}

    	else{
    		return redirect()->back();
    	}

    }

    public function deleteContactMessage(Request $request)
    {   
            $message_id = 0;
        $get_message = contactMessage::find($request->message_id);
        if ($get_message) {
            $message_id = $get_message->id;
            
            
            $get_message->deleted_by = Auth::User()->id;
            $get_message->save();

            $get_message->delete();
Session::flash('message_deleted','Message Deleted successfully !'.$message_id);
            return redirect()->back();
            
        }

        else{
            return redirect()->back();
        }
    }

    public function undoDeleteContactMessage($id)
    {
        $get_message = DB::table('contact_messages')->where('id',$id)->first();
        if ($get_message) {
             
             DB::table('contact_messages')
            ->where('id', $id)
            ->update(['deleted_at' => NULL , 'deleted_by' => 0]);


            Session::flash('undo_successfully','Message Not Deleted !');
            return redirect()->back();

        }

        else{
            return redirect()->back();
        }
        
    }
}

public_html/resources/views/back_end/projects/create.blade.php
@include('back_end.app')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Create New Project
            
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            
            <li class="active">Create New Project</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            
              <div class="col-md-12">
                 @if ($errors->any())
    <div class="alert alert-warning alert-dismissable">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br>
@endif
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">New Project</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="{{route('projects.store')}}" enctype="multipart/form-data">
                  {{csrf_field()}}
                  <div class="box-body">
                    <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                      <label for="exampleInputFile">Choose Project Image</label>
              <input type="file" class="form-control" name="image">
                    
                    </div>
                    </div>
                    <div class="col-md-6">
                      
                      <div class="form-group">
                      <label for="exampleInputEmail1">Project Name</label>
                      <input type="text" class="form-control" name="project_name" value="{{old('project_name')}}">
                    </div> 
                    </div>
                  </div>
                    <div class="row">
                     

                    <div class="col-md-6">
                      
                      <div class="form-group">
                      <label for="exampleInputEmail1">Project Main Subject</label>
                      <input type="text" class="form-control" name="project_main_subject" value="{{old('project_main_subject')}}">
                    </div> 
                    </div>

                    <div class="col-md-6">
                      
                      <div class="form-group">
                      <label for="exampleInputEmail1">Project Description</label>
                     
                 <textarea class="form-control" name="project_description" value="{{old('project_description')}}" rows="5" cols="30" style="resize: none;">
                   
                 </textarea>
                    </div> 
                    </div>
                   </div>
                     

                    </div>
                    
                   <div class="box-footer">
                      <button type="submit" class="btn btn-success btn-block">Create Project</button>
                    </div>
                  </div><!-- /.box-body -->

                 
                </form>
              </div><!-- /.box -->

    

           
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
@include('back_end.footer')

public_html/resources/views/back_end/projects/edit.blade.php
@include('back_end.app')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            {{$get_project->name}}

                
            
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            
            <li class="active">Edit Project</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="col-xs-12">
          <div class="row">
             @if(session()->has('image_uploade'))
   <div class="alert alert-success">{{ session('image_uploade') }}</div>
         @endif

         @if(session()->has('updated'))
   <div class="alert alert-success">{{ session('updated') }}</div>
         @endif

         
      

         


          @if ($errors->any())
    <div class="alert alert-warning alert-dismissable">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br>
@endif

 <div class="col-md-12">
              
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Project Information</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                  
                  <div class="box-body">
                    <div class="row">
                      <form method="post" action="/update_project" enctype="multipart/form-data">
                        {{csrf_field()}}
                    <div class="col-md-12">
                      <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                        <label>Project Name</label>
                        <input type="text" name="name" value="{{$get_project->name}}" class="form-control">
                      </div>
                      </div>
                     <div class="col-md-6">
                      <div class="form-group">
                        <label>Project Main Subject</label>
                        <input type="text" name="project_main_subject" value="{{$get_project->project_main_subject}}" class="form-control">
                      </div>
                    </div>

                   
</div>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
    <label>Choose Project Video</label>
    <input type="file" name="image" class="form-control">
  </div>
  </div>

    <div class="col-md-6">
                      <div class="form-group">
                        <label>Project Description</label>
                  <textarea class="form-control" rows="5" cols="30" name="project_description" style="resize: none;">
                        {{$get_project->project_description}}
                  </textarea>
                      </div>
                    </div>
</div>
<input type="hidden" name="project_id" value="{{$get_project->id}}">
<input type="submit" name="submit" value="Edit Project" class="btn btn-block btn-primary btn-lg">
                    </div>
                  </form>
                    
              
</div>
                    </div>
                    
                              </div><!-- /.box-body -->

                 
                
              </div><!-- /.box -->

     

           </div>
            </div><!-- /.col -->



              <div class="row">

          </div><!-- /.row --> 
        
        </section><!-- /.content -->
      
      </div><!-- /.content-wrapper -->
@include('back_end.footer')

public_html/resources/views/back_end/projects/index.blade.php
@include('back_end.app')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            View All Projects
            
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            
            <li class="active">All Projects</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
            	 @if ($errors->any())
    <div class="alert alert-warning alert-dismissable">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br>
@endif

            
  @if(session()->has('delete_project'))
   <div class="alert alert-danger"> Project deleted successfully <a href="/undo_delete_project/{{ session('delete_project') }}">Undo</a> </div>
         @endif

  @if(session()->has('undo_delete_project'))

  <div class="alert alert-success">{{ session('delete_project') }}</div>
  @endif



	         
              
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">All Projects</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Project name</th>
                        <th>Project Main Video</th>
                         
                        <th>Added by</th>
                        <th>Created At</th>
                        <th>Actions</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($get_all_projects as $project)
                      <tr>
                        <td>{{$project->name}}</td>
                        <td>
                           <video width="300px;" height="200px;" controls controlsList="nodownload">
  <source src="{{Storage::url($project->project_image_path)}}" type="video/mp4">
</video>
                          
                        </td>
                        
                        
                        <td>
                        {{$project->AddedBy->name}}
                      </td>
                        <td>
                          {{$project->created_at}}
                          </td>
                          
                    
                       
                    
                        <td>
                        	<a href="/projects/{{$project->id}}" class="btn btn-info btn-md">View Project</a>
                          <br>

                        <a href="/projects/edit/{{$project->id}}" class="btn btn-warning btn-md">Edit Project</a>
                        <br>
                        <a href="/delete_project/{{$project->id}}" class="btn btn-danger btn-md">Delete Project</a>
                        </td>
                        
                      </tr>
                      @endforeach 
                    </tbody>
                   
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
@include('back_end.footer')

public_html/resources/views/back_end/projects/show.blade.php
@include('back_end.app')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            {{$get_project->name}}

                
            
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            
            <li class="active">Project</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="col-xs-12">
          <div class="row">
             @if(session()->has('image_uploade'))
   <div class="alert alert-success">{{ session('image_uploade') }}</div>
         @endif

         @if(session()->has('success_added_image'))
   <div class="alert alert-success">{{ session('success_added_image') }}</div>
         @endif

          @if(session()->has('updated'))
   <div class="alert alert-success">{{ session('updated') }}</div>
         @endif
         
      

          @if(session()->has('delete_photo'))
   <div class="alert alert-danger"> Image deleted successfully <a href="/undo_delete_project_image/{{ session('delete_photo') }}">Undo</a> </div>
         @endif


          @if ($errors->any())
    <div class="alert alert-warning alert-dismissable">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br>
@endif
          
            <?php /* ?>  <div class="col-md-3">
              
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Upload Project Photos</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="/upload_project_image" enctype="multipart/form-data">
                  {{csrf_field()}}
                  <div class="box-body">
                    <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                      <label for="exampleInputFile">Choose File</label>
              <input type="file" class="form-control" name="file[]" multiple="true">
              <input type="hidden" name="project_id" value="{{$get_project->id}}">
                    
                    </div>
                    </div>
                    
              
</div>
                    </div>
                    
                   <div class="box-footer">
                      <button type="submit" class="btn btn-success btn-block">Upload File</button>
                    </div>
                    </form>
                  </div><!-- /.box-body -->

                 
                
              </div><!-- /.box -->  */ ?>
 <div class="col-md-12">
              
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Project Information</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                  
                  <div class="box-body">
                    <div class="row">
                    <div class="col-md-12">
                <tr><b>Added By : </b> {{$get_project->AddedBy->name}}</tr>
              @if($get_project->updated_by != 0 and $get_project->updated_by != NULL)
              <br>
              <br>
              <tr><b>Updated By : </b> {{$get_project->UpdatedBy->name}}</tr>
              @endif
              <br>
              <br>
              <tr><b>Project Date And Time : </b> {{$get_project->created_at}}</tr>
              <br>
              <br>
              @if($get_project->project_main_subject != NULL)
              <tr><b>Project Main Subject: </b> {{$get_project->project_main_subject}}</tr>
              <br><br>
              @endif
              @if($get_project->project_description != NULL)
              <tr><b>Project Description :</b> 
                <?php 

                $desc = $get_project->project_description;
               
                $y = str_replace(':','</h3>',$desc );
            $x = str_replace('.',"\n",$desc );
              $z = nl2br($x);
                 ?>
                 <div>
                  <?php echo $z; ?>        
                   
                 </div>
             

              </tr>
              <br>
              <br>
              @endif
              <tr><b>Project Video : </b> 
<button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#document_video">View Video</button>

<a href="/projects/edit/{{$get_project->id}}" class="btn btn-warning btn-md">Edit Project</a>

                    </div>
                    
              
</div>
                    </div>
                    
                    </form>
                  </div><!-- /.box-body -->

                 
                
              </div><!-- /.box -->

     

           </div>
            </div><!-- /.col -->



              <div class="row">

                <div class="col-md-12">
                  <a href="/projects" class="btn btn-md btn-block btn-primary">Back To Projects</a>
                </div>
            <?php /* ?>    @foreach($get_all_images_in_project as $photo)
            <div class="col-md-4">
              <!-- Default box -->

              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">
                    <a href="/delete_project_image/{{$photo->id}}" class="btn btn-md btn-danger">Delete</a>
                  </h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
                <div class="box-body" style="display: block;">

                  
                  <p>
                     <?php $tmp = explode('.',$photo->project_image);
                $extention = end($tmp);
           ?>
           @if($extention == 'png' or $extention == 'jpg' or $extention == 'jpeg')
        
        <img src="{{Storage::url($photo->project_image)}}" width="300px;" height="300px;">
      
        @elseif($extention == 'mp4' or $extention == 'flv')
        <video width="300px;" height="300px;" controls controlsList="nodownload">
  <source src="{{Storage::url($photo->project_image)}}" type="video/mp4">
</video>
        @endif
                    
                  </p>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
            @endforeach
          </div><?php */ ?>
          </div><!-- /.row --> 
        
        </section><!-- /.content -->
      
      </div><!-- /.content-wrapper -->

      <!-- Modal -->
<div id="document_video" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">{{$get_project->name}} Video </h4>
      </div>
      <div class="modal-body">
        <center>

       <video width="500px;" height="500px;" controls controlsList="nodownload">
  <source src="{{Storage::url($get_project->project_image_path)}}" type="video/mp4">
</video>
        </center>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
@include('back_end.footer')