public_html/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
});


Route::get('/videos',function(){
	$get_all_videos = App\Video::orderBy('id','desc')->get();
	return view('front_end.videos')->with('get_all_videos',$get_all_videos);
});


Route::get('/', function () {
    return view('index');
});

Route::get('/register',function(){
	abort(404);
});

Route::get('/company_projects','ProjectContoller@companyProjects');
//Route::get('/company_projects/{id}','ProjectContoller@companyProjectDetail');


Route::get('/company_documents/{id}','DocumentController@getOneDocument');

Route::get('/about_us','FrontEndController@aboutUs');
Route::get('/contact_us','FrontEndController@contactUs');
Route::post('/send_message_contact_us','FrontEndController@sendMessageContactUs');
Route::get('logout', 'Auth\LoginController@logout');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('forget_password', function()
{   if (Route::has('login')) {
        if (Auth::check()) {
            return redirect('/login');
    
}
return view('front_end.forget_password'); 
}
});
	
Route::get('/company_documents','DocumentController@allDocumentsFrontEnd');

Route::get('/photos','FrontEndController@allPhotos');
Route::get('album','FrontEndController@allAlbums');
Route::get('album/{id}','FrontEndController@photoAlbum');
Route::get('/google74b7c7d77aa0b104.html',function(){

return view('google_file');
});

Route::group(['middleware' => ['auth']], function () {
Route::get('/contact_us_messages','BackEndController@getContactUsMessages');    
Route::post('/set_message_read','BackEndController@markMessageRead');
Route::get('/create_user','UserController@createUser');
Route::get('/all_users','UserController@viewUsers');
Route::post('/add_user','UserController@addUser');
Route::get('edit_user/{id}','UserController@editUser');
Route::post('/update_user','UserController@updateUser');
Route::post('/delete_contact_message','BackEndController@deleteContactMessage');
Route::get('/undo_contact_message_delete/{id}','BackEndController@undoDeleteContactMessage');
Route::get('/create_slider_show','FrontEndController@createSliderShow');
Route::get('/all_slider_show','FrontEndController@getAllSliderShowImges');
Route::post('/upload_new_slider_show','FrontEndController@uploadNewSliderShow');
Route::post('/end_slide_show','FrontEndController@endSliderShow');
Route::post('/delete_slider_image','FrontEndController@deleteSliderImage');
Route::get('/undo_delete_slider/{id}','FrontEndController@undoDeleteSliderImage');
Route::get('/my_profile','ProfileController@myProfile');
Route::post('/upload_profile_photo','ProfileController@uploadProfilePhotos');
Route::post('/change_my_password','ProfileController@changePassword');
Route::get('/set_image_default/{id}','ProfileController@setImageDefault');
Route::get('/delete_profile_image/{id}','ProfileController@deleteProfileImage');
Route::get('/upload_video','VideoController@uploadVideo');
Route::post('/upload_new_video','VideoController@uploadNewVideo');
Route::get('/all_videos','VideoController@allVideos');
Route::post('/delete_video','VideoController@deleteVideo');
Route::get('/undo_delete_video/{id}','VideoController@undoDeleteVideo');
Route::get('/all_documents','DocumentController@allDocuments');
Route::get('/document/{id}','DocumentController@oneDocument');
Route::post('/add_document','DocumentController@addDocument');
Route::get('/create_document','DocumentController@createDocument');
//Route::get('/create_photo','PhotoController@createPhoto');
//Route::get('/all_photos','PhotoController@allPhotos');
Route::post('/add_photo','PhotoController@addPhoto');
Route::get('/delete_photo/{id}','PhotoController@deletePhoto');
Route::get('/undo_delete_photo/{id}','PhotoController@undoDeletePhoto');
Route::post('/change_my_name','ProfileController@changeName');
Route::get('/message/{id}','FrontEndController@getMessage');
Route::post('/upload_document_image','DocumentController@uploadDocumentImage');
Route::get('/delete_document_image/{id}','DocumentController@deleteDocumentImage');
Route::get('/undo_delete_document_image/{id}','DocumentController@undoDeleteDocumentPhoto');
Route::post('/edit_document_name','DocumentController@update');
Route::resource('projects','ProjectContoller');
Route::post('/upload_project_image','ProjectContoller@uploadImage');
Route::get('/delete_project_image/{id}','ProjectContoller@deleteProjectImage');
Route::get('/undo_delete_project_image/{id}','ProjectContoller@undoDeleteProjectImage');
Route::get('/active_user/{id}','UserController@Activation');
Route::post('/delete_documents','DocumentController@deleteDocuments');
Route::get('/undo_document_delete/{id}','DocumentController@undoDeleteDocument');
Route::get('/set_first_slider/{id}','FrontEndController@setSliderFirst');
Route::get('/projects/edit/{id}','ProjectContoller@editProject');
Route::post('/update_project','ProjectContoller@updateProject');
Route::get('/delete_project/{id}','ProjectContoller@deleteProject');
Route::get('/undo_delete_project/{id}','ProjectContoller@undoDeleteProject');
Route::resource('last_news','LastNewsController');
Route::post('/update_news','LastNewsController@updateNews');
Route::get('delete_news/{id}','LastNewsController@destroy');
Route::get('/undo_delete_news/{id}','LastNewsController@undoDeleteNews');
Route::get('/active_news/{id}','LastNewsController@activeNews');
Route::resource('albums','AlbumController');
Route::post('/update_album','AlbumController@updateAlbum');
Route::get('/active_album/{id}','AlbumController@activeAlbum');
Route::post('/change_album','AlbumController@changeAlbum');
Route::get('test_slider','DocumentController@testSlider');
});

public_html/app/Album.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Album extends Model
{
  	
  	use SoftDeletes;
  public function AddedBy()
    {
    	return $this->hasOne('App\User','id','added_by');
    }

    public function DeletedBy()
    {
    	return $this->hasOne('App\User','id','deleted_by');
    } 

    public function UpdatedBy()
    {
    	return $this->hasOne('App\User','id','updated_by');
    }  
}

public_html/app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Album;
use Auth;
use Session;
use DB;
use App\Photo;
class AlbumController extends Controller
{
   
    public function index()
    {
        $get_all_albums = Album::orderBy('id','desc')->get();
        return view('back_end/albums.index')->with('get_all_albums',$get_all_albums);
        
    }

    
    public function create()
    {
         return view('back_end/albums.create');
        
    }

    
    public function store(Request $request)
    {
       $this->validate($request,array(

        'album_name' => 'required|unique:albums',
       
       ));

       $new_album = new Album;
       $new_album->album_name = $request->album_name;
       $new_album->added_by = Auth::User()->id;
       $new_album->save();

       Session::flash('album_created','Album created successfully');
       return redirect()->route('albums.show',$new_album->id);
    }

    public function show($id)
    {
        $find_album = Album::find($id);
        if ($find_album) {
          $get_all_photos_in_album = Photo::where('album_id',$id)->orderBy('id','desc')->get();
          return view('back_end/albums.show')->with('find_album',$find_album)->with('get_all_photos_in_album',$get_all_photos_in_album);  
        }

        else{
            return redirect()->route('albums.index');
        }
       
    }

    public function updateAlbum(Request $request)
    {
        $this->validate($request,array(

        'album_name' => "required|unique:albums,album_name,$request->album_id",
       
       ));
        $find_album = Album::find($request->album_id);
        if ($find_album) {
          
          $find_album->album_name = $request->input('album_name');
          $find_album->updated_by = Auth::User()->id;
          $find_album->save();

          Session::flash('updated','Album name updated successfully');
          return redirect()->back();  

        }
        else{
            return redirect()->back();
        }
        
    }

    public function activeAlbum($id)
    {
     $find_album = Album::find($id);
     if ($find_album) {
       if ($find_album->active == 1) {
        
        $find_album->active = 0;
        $find_album->updated_by = Auth::User()->id;
        $find_album->save();
        Session::flash('active','Album Deactivated successfully');
        return redirect()->back();     
      } 

        elseif ($find_album->active == 0) {
          $find_album->active = 1;
        $find_album->updated_by = Auth::User()->id;
        $find_album->save();
        Session::flash('active','Album active successfully');
        return redirect()->back(); 
        }

        }
        else{
          return redirect()->back();
        }
    }

    
    public function edit($id)
    {
        //
    }

   
    public function update(Request $request, $id)
    {
        
    }

    
    public function destroy($id)
    {
        
    }

    public function changeAlbum(Request $request)
    {
      $find_album = Album::find($request->album_id);
      $find_photo = Photo::find($request->photo_id);

      if ($find_photo and $find_album) {
        
        $find_photo->album_id = $request->album_id;
        $find_photo->save();
        Session::flash('image_upload','Album set successfully');
        return redirect()->back();
      }

      else{
        return redirect()->back();
      }
    }
}

public_html/app/Http/Controllers/BackEndController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\contactMessage;
use Session;
use Auth;
use App\User;
use DB;
class BackEndController extends Controller
{
    public function getContactUsMessages()
    {
    	$get_all_messages = contactMessage::all();
    	return view('back_end.contact_us_messages')->with('get_all_messages',$get_all_messages);
    }

    public function markMessageRead(Request $request)
    {
    	$get_message = contactMessage::find($request->message_id);
    	if ($get_message) {
    		
    			
    		if ($get_message->read_or_not == 0) {
    			$get_message->read_or_not = 1 ;
    			$get_message->read_by = Auth::User()->id;
    			$get_message->save();
    			Session::flash('message_read','Message successfully read !');
    			return redirect()->back();		
    	}

    		elseif ($get_message->read_or_not == 1) {

    			$get_message->read_or_not = 0 ;
    			$get_message->read_by = 0;
    			$get_message->save();
    			Session::flash('message_read','Message successfully Not read !');
    			return redirect()->back();		
    		}	
    	}

    	else{
    		return redirect()->back();
    	}

    }

    public function deleteContactMessage(Request $request)
    {   
            $message_id = 0;
        $get_message = contactMessage::find($request->message_id);
        if ($get_message) {
            $message_id = $get_message->id;
            
            
            $get_message->deleted_by = Auth::User()->id;
            $get_message->save();

            $get_message->delete();
Session::flash('message_deleted','Message Deleted successfully !'.$message_id);
            return redirect()->back();
            
        }

        else{
            return redirect()->back();
        }
    }

    public function undoDeleteContactMessage($id)
    {
        $get_message = DB::table('contact_messages')->where('id',$id)->first();
        if ($get_message) {
             
             DB::table('contact_messages')
            ->where('id', $id)
            ->update(['deleted_at' => NULL , 'deleted_by' => 0]);


            Session::flash('undo_successfully','Message Not Deleted !');
            return redirect()->back();

        }

        else{
            return redirect()->back();
        }
        
    }
}

public_html/resources/views/back_end/albums/create.blade.php
@include('back_end.app')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Create New Album
            
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            
            <li class="active">Create New Album</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            
              <div class="col-md-12">
                 @if ($errors->any())
    <div class="alert alert-warning alert-dismissable">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br>
@endif
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">New Album</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="{{route('albums.store')}}">
                  {{csrf_field()}}
                  <div class="box-body">
                    <div class="row">
                   
                    <div class="col-md-6">
                      
                      <div class="form-group">
                      <label for="exampleInputEmail1">Album Name</label>
                      <input type="text" class="form-control" name="album_name" value="{{old('album_name')}}">
                    </div> 
                    </div>
                   
                     
</div>
                    </div>
                    
                   <div class="box-footer">
                      <button type="submit" class="btn btn-success btn-block">Create Album</button>
                    </div>
                  </div><!-- /.box-body -->

                 
                </form>
              </div><!-- /.box -->

    

           
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
@include('back_end.footer')

public_html/resources/views/back_end/albums/index.blade.php
@include('back_end.app')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            View All Albums
            
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            
            <li class="active">All Albums</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
            	 @if ($errors->any())
    <div class="alert alert-warning alert-dismissable">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br>
@endif

 @if(session()->has('active'))
   <div class="alert alert-success">{{ session('active') }}</div>
         @endif
           


	         
              
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">All Albums</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Album name</th>
                        <th>Status</th>
                        <th>Added by</th>
                        <th>Created At</th>
                        <th>Actions</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($get_all_albums as $album)
                      <tr>
                        <td>{{$album->album_name}}</td>
                        <td>
                          @if($album->active == 1)
                          Active
                          @elseif($album->active == 0)
                          Not Active
                          @endif
                        </td>
                        
                        <td>
                        {{$album->AddedBy->name}}
                      </td>
                        <td>
                          {{$album->created_at}}
                          </td>
                          
                    
                       
                    
                        <td>
                        	<a href="albums/{{$album->id}}" class="btn btn-info btn-md">View Album</a>
                          @if($album->active == 1)
                    <a href="/active_album/{{$album->id}}" class="btn btn-warning btn-md">Deactive</a>
                    @elseif($album->active == 0)
                     <a href="/active_album/{{$album->id}}" class="btn btn-success btn-md">Active</a>
                     @endif
                        </td>
                      </tr>
                      @endforeach 
                    </tbody>
                   
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
@include('back_end.footer')

public_html/resources/views/back_end/albums/show.blade.php
@include('back_end.app')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            {{$find_album->album_name}}

                
            
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            
            <li class="active">Album</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="col-xs-12">
          <div class="row">
             @if(session()->has('image_upload'))
   <div class="alert alert-success">{{ session('image_upload') }}</div>
         @endif

         @if(session()->has('updated'))
   <div class="alert alert-success">{{ session('updated') }}</div>
         @endif

@if(session()->has('choose_image'))
   <div class="alert alert-warning">{{ session('choose_image') }}</div>
         @endif
         
      

          @if(session()->has('delete_photo'))
   <div class="alert alert-danger"> Image deleted successfully <a href="/undo_delete_document_image/{{ session('delete_photo') }}">Undo</a> </div>
         @endif


          @if ($errors->any())
    <div class="alert alert-warning alert-dismissable">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br>
@endif
          
             
 <div class="col-md-6">
              
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Album Information</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                  
                  <div class="box-body">
                    <div class="row">
                    <div class="col-md-12">
                      <div class="row">
                        <div class="col-md-4">
                         <b>Album Name : </b>
                      </div>  <form action="/update_album" method="post">
                      <div class="col-md-4">
                       
                          {{csrf_field()}}
                          <input type="hidden" name="album_id" value="{{$find_album->id}}">
                        <input type="text" name="album_name" class="form-control" value="{{$find_album->album_name}}">
                      </div>
                      <div class="col-md-4">
                        <input type="submit" name="submit" class="btn btn-primary btn-md" value="Change Name">

                      </div>
                    </form>
                    </div>
             
              <tr><b>Added By : </b> {{$find_album->AddedBy->name}}</tr>
              @if($find_album->updated_by != 0 and $find_album->updated_by != NULL)
              <br>
              <br>
              <tr><b>Updated By : </b> {{$find_album->UpdatedBy->name}}</tr>
              @endif
             
             


                    </div>
                    
              
</div>
                    </div>
                    
                   
                  </div><!-- /.box-body -->

                 
                
              </div><!-- /.box -->

      <div class="col-md-6">
              
              <!-- general form elements -->
               <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">New Photo</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="/add_photo" enctype="multipart/form-data">
                  {{csrf_field()}}
                  <div class="box-body">
                    <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                      <label for="exampleInputFile">Choose Photo</label>
              <input type="file" class="form-control" name="file[]" multiple="true">
                    <input type="hidden" name="album_id" value="{{$find_album->id}}">
                    </div>
                    </div>
                
            
</div>
                    </div>
                    
                   <div class="box-footer">
                      <button type="submit" class="btn btn-success btn-block">Upload Photos</button>
                    </div>
                  </div><!-- /.box-body -->
                 
                
              </div><!-- /.box -->

           </div>
<a href="/albums" class="btn btn-block btn-info btn-md">Back To All Albums</a>
<br>
            
            </div><!-- /.col -->







              <div class="row">
                @foreach($get_all_photos_in_album as $photo)
            <div class="col-md-4">
              <!-- Default box -->

              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">
                    <a href="/delete_photo/{{$photo->id}}" class="btn btn-md btn-danger">Delete</a>
                  </h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
                <div class="box-body" style="display: block;">
                  
                  <p>
                   <img src="{{Storage::url($photo->image_path)}}" height="300px" width="300px"> 
                  </p>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
            @endforeach
          </div> 
          </div><!-- /.row -->
        
        </section><!-- /.content -->
      
      </div><!-- /.content-wrapper -->

   

@include('back_end.footer')