public_html/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
});


Route::get('/videos',function(){
	$get_all_videos = App\Video::orderBy('id','desc')->get();
	return view('front_end.videos')->with('get_all_videos',$get_all_videos);
});


Route::get('/', function () {
    return view('index');
});

Route::get('/register',function(){
	abort(404);
});

Route::get('/company_projects','ProjectContoller@companyProjects');
//Route::get('/company_projects/{id}','ProjectContoller@companyProjectDetail');


Route::get('/company_documents/{id}','DocumentController@getOneDocument');

Route::get('/about_us','FrontEndController@aboutUs');
Route::get('/contact_us','FrontEndController@contactUs');
Route::post('/send_message_contact_us','FrontEndController@sendMessageContactUs');
Route::get('logout', 'Auth\LoginController@logout');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('forget_password', function()
{   if (Route::has('login')) {
        if (Auth::check()) {
            return redirect('/login');
    
}
return view('front_end.forget_password'); 
}
});
	
Route::get('/company_documents','DocumentController@allDocumentsFrontEnd');

Route::get('/photos','FrontEndController@allPhotos');
Route::get('album','FrontEndController@allAlbums');
Route::get('album/{id}','FrontEndController@photoAlbum');
Route::get('/google74b7c7d77aa0b104.html',function(){

return view('google_file');
});

Route::group(['middleware' => ['auth']], function () {
Route::get('/contact_us_messages','BackEndController@getContactUsMessages');    
Route::post('/set_message_read','BackEndController@markMessageRead');
Route::get('/create_user','UserController@createUser');
Route::get('/all_users','UserController@viewUsers');
Route::post('/add_user','UserController@addUser');
Route::get('edit_user/{id}','UserController@editUser');
Route::post('/update_user','UserController@updateUser');
Route::post('/delete_contact_message','BackEndController@deleteContactMessage');
Route::get('/undo_contact_message_delete/{id}','BackEndController@undoDeleteContactMessage');
Route::get('/create_slider_show','FrontEndController@createSliderShow');
Route::get('/all_slider_show','FrontEndController@getAllSliderShowImges');
Route::post('/upload_new_slider_show','FrontEndController@uploadNewSliderShow');
Route::post('/end_slide_show','FrontEndController@endSliderShow');
Route::post('/delete_slider_image','FrontEndController@deleteSliderImage');
Route::get('/undo_delete_slider/{id}','FrontEndController@undoDeleteSliderImage');
Route::get('/my_profile','ProfileController@myProfile');
Route::post('/upload_profile_photo','ProfileController@uploadProfilePhotos');
Route::post('/change_my_password','ProfileController@changePassword');
Route::get('/set_image_default/{id}','ProfileController@setImageDefault');
Route::get('/delete_profile_image/{id}','ProfileController@deleteProfileImage');
Route::get('/upload_video','VideoController@uploadVideo');
Route::post('/upload_new_video','VideoController@uploadNewVideo');
Route::get('/all_videos','VideoController@allVideos');
Route::post('/delete_video','VideoController@deleteVideo');
Route::get('/undo_delete_video/{id}','VideoController@undoDeleteVideo');
Route::get('/all_documents','DocumentController@allDocuments');
Route::get('/document/{id}','DocumentController@oneDocument');
Route::post('/add_document','DocumentController@addDocument');
Route::get('/create_document','DocumentController@createDocument');
//Route::get('/create_photo','PhotoController@createPhoto');
//Route::get('/all_photos','PhotoController@allPhotos');
Route::post('/add_photo','PhotoController@addPhoto');
Route::get('/delete_photo/{id}','PhotoController@deletePhoto');
Route::get('/undo_delete_photo/{id}','PhotoController@undoDeletePhoto');
Route::post('/change_my_name','ProfileController@changeName');
Route::get('/message/{id}','FrontEndController@getMessage');
Route::post('/upload_document_image','DocumentController@uploadDocumentImage');
Route::get('/delete_document_image/{id}','DocumentController@deleteDocumentImage');
Route::get('/undo_delete_document_image/{id}','DocumentController@undoDeleteDocumentPhoto');
Route::post('/edit_document_name','DocumentController@update');
Route::resource('projects','ProjectContoller');
Route::post('/upload_project_image','ProjectContoller@uploadImage');
Route::get('/delete_project_image/{id}','ProjectContoller@deleteProjectImage');
Route::get('/undo_delete_project_image/{id}','ProjectContoller@undoDeleteProjectImage');
Route::get('/active_user/{id}','UserController@Activation');
Route::post('/delete_documents','DocumentController@deleteDocuments');
Route::get('/undo_document_delete/{id}','DocumentController@undoDeleteDocument');
Route::get('/set_first_slider/{id}','FrontEndController@setSliderFirst');
Route::get('/projects/edit/{id}','ProjectContoller@editProject');
Route::post('/update_project','ProjectContoller@updateProject');
Route::get('/delete_project/{id}','ProjectContoller@deleteProject');
Route::get('/undo_delete_project/{id}','ProjectContoller@undoDeleteProject');
Route::resource('last_news','LastNewsController');
Route::post('/update_news','LastNewsController@updateNews');
Route::get('delete_news/{id}','LastNewsController@destroy');
Route::get('/undo_delete_news/{id}','LastNewsController@undoDeleteNews');
Route::get('/active_news/{id}','LastNewsController@activeNews');
Route::resource('albums','AlbumController');
Route::post('/update_album','AlbumController@updateAlbum');
Route::get('/active_album/{id}','AlbumController@activeAlbum');
Route::post('/change_album','AlbumController@changeAlbum');
Route::get('test_slider','DocumentController@testSlider');
});

public_html/app/LastNews.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class LastNews extends Model
{
    use SoftDeletes;


    public function AddedBy()
    {
    	return $this->hasOne('App\User','id','added_by');
    }

    public function FunctionName()
    {
    	return $this->hasOne('App\User','id','deleted_by');
    }
}

public_html/app/Http/Controllers/BackEndController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\contactMessage;
use Session;
use Auth;
use App\User;
use DB;
class BackEndController extends Controller
{
    public function getContactUsMessages()
    {
    	$get_all_messages = contactMessage::all();
    	return view('back_end.contact_us_messages')->with('get_all_messages',$get_all_messages);
    }

    public function markMessageRead(Request $request)
    {
    	$get_message = contactMessage::find($request->message_id);
    	if ($get_message) {
    		
    			
    		if ($get_message->read_or_not == 0) {
    			$get_message->read_or_not = 1 ;
    			$get_message->read_by = Auth::User()->id;
    			$get_message->save();
    			Session::flash('message_read','Message successfully read !');
    			return redirect()->back();		
    	}

    		elseif ($get_message->read_or_not == 1) {

    			$get_message->read_or_not = 0 ;
    			$get_message->read_by = 0;
    			$get_message->save();
    			Session::flash('message_read','Message successfully Not read !');
    			return redirect()->back();		
    		}	
    	}

    	else{
    		return redirect()->back();
    	}

    }

    public function deleteContactMessage(Request $request)
    {   
            $message_id = 0;
        $get_message = contactMessage::find($request->message_id);
        if ($get_message) {
            $message_id = $get_message->id;
            
            
            $get_message->deleted_by = Auth::User()->id;
            $get_message->save();

            $get_message->delete();
Session::flash('message_deleted','Message Deleted successfully !'.$message_id);
            return redirect()->back();
            
        }

        else{
            return redirect()->back();
        }
    }

    public function undoDeleteContactMessage($id)
    {
        $get_message = DB::table('contact_messages')->where('id',$id)->first();
        if ($get_message) {
             
             DB::table('contact_messages')
            ->where('id', $id)
            ->update(['deleted_at' => NULL , 'deleted_by' => 0]);


            Session::flash('undo_successfully','Message Not Deleted !');
            return redirect()->back();

        }

        else{
            return redirect()->back();
        }
        
    }
}

public_html/app/Http/Controllers/LastNewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\LastNews;
use Auth;
use Session;
use DB;
class LastNewsController extends Controller
{
   
    public function index()
    {
    	$get_all_news = LastNews::orderBy('id','desc')->get();

    	return view('back_end/last_news.index')->with('get_all_news',$get_all_news);       
    }

    
    public function create()
    {
      return view('back_end/last_news.create');  
    }

    
    public function store(Request $request)
    {
    	$validatedData = $request->validate([
        'description' => 'required',
        'main_subject' => 'required',
    ]);

    	$new_news = new LastNews;
    	$new_news->description = $request->description;
    	$new_news->main_subject = $request->main_subject;
    	$new_news->added_by = Auth::User()->id;
    	$new_news->active = 1;
    	$new_news->save();

    	Session::flash('news_added','News Added successfully');
    	return redirect()->route('last_news.show',$new_news->id);
     
     return $request;   
    }

    
    public function show($id)
    {
    	$get_one_news = LastNews::find($id);
    	if ($get_one_news) {
    	return view('back_end/last_news.show')->with('get_one_news',$get_one_news);	
    	}

    	else{
		return redirect()->route('last_news.index');
    	}
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    public function updateNews(Request $request)
    {
    	$find_news = LastNews::find($request->news_id);
    	if ($find_news) {
    	$validatedData = $request->validate([
        'description' => 'required',
        'main_subject' => 'required',
    ]);

    		$find_news->description = $request->input('description');
    		$find_news->main_subject = $request->input('main_subject');
    		$find_news->save();

    		Session::flash('news_added','News updated successfully');
    		return redirect()->back();
    	}
    }

   	
    public function undoDeleteNews($id)
    {

    	$find_news = DB::table('last_news')->where('id',$id)->first();

    	if ($find_news) {
    		

    		if ($find_news->deleted_at != NULL) {
    		
    		DB::table('last_news')
    		->where('id',$id)->update(['deleted_at' => NULL , 'deleted_by' => 0]);

    		Session::flash('undo_success','Undo successfully');
    		return redirect()->back();	
    		}

    		else{
    			return redirect()->back();
    		}
    	}

    	else{
    		return redirect()->back();
    	}
    	
    }

    public function destroy($id)
    {
        $find_news = LastNews::find($id);
        if ($find_news) {
        	$news_id = $id;
        	$find_news->deleted_by = Auth::User()->id;
        	$find_news->save();
        	$find_news->delete();

        	Session::flash('delete_news',$news_id);
        	return redirect()->route('last_news.index');
        	
        }

        else{
        	return redirect()->back();
        }
    }

    public function activeNews($id)
    {
        
        $find_news = LastNews::find($id);
        if ($find_news) {
            if ($find_news->active == 1) {
            
                $find_news->active = 0;
                $find_news->save();
                Session::flash('active_news','News deactive successfully');
                return redirect()->back();
            }
            elseif($find_news->active == 0){
                 $find_news->active = 1;
                $find_news->save();
                Session::flash('active_news','News active successfully');
                return redirect()->back();
            }

        }

        else{
            return redirect()->back();
        }
    }
}

public_html/resources/views/back_end/last_news/create.blade.php
@include('back_end.app')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Create New News
            
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            
            <li class="active">Create New News</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            
              <div class="col-md-12">
                 @if ($errors->any())
    <div class="alert alert-warning alert-dismissable">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br>
@endif
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">New News</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" action="{{route('last_news.store')}}">
                  {{csrf_field()}}
                  <div class="box-body">
                    <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                      <label for="exampleInputFile">News Main Subject</label>
                <input type="text" name="main_subject" class="form-control" value="{{old('main_subject')}}">
                    
                    </div>
                    </div>
                    <div class="col-md-6">
                      
                      <div class="form-group">
                      <label>News Description</label>
                   <textarea class="form-control" name="description" value="{{old('description')}}" rows="5" cols="30" style="resize: none;">
                   
                 </textarea>
                    </div> 
                    </div>
                  </div>
                    
                     

                    </div>
                    
                   <div class="box-footer">
                      <button type="submit" class="btn btn-success btn-block">Create News</button>
                    </div>
                  </div><!-- /.box-body -->

                 
                </form>
              </div><!-- /.box -->

    

           
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
@include('back_end.footer')

public_html/resources/views/back_end/last_news/index.blade.php
@include('back_end.app')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            View All Last News
            
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            
            <li class="active">All News</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
            	 @if ($errors->any())
    <div class="alert alert-warning alert-dismissable">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br>
@endif

             @if(session()->has('delete_news'))
   <div class="alert alert-danger">News deleted successfully ! <a href="/undo_delete_news/{{ session('delete_news') }}">Undo</a></div>
         @endif

          @if(session()->has('undo_success'))
   <div class="alert alert-success">{{ session('undo_success') }}</div>
         @endif
         
         @if(session()->has('active_news'))
   <div class="alert alert-success">{{ session('active_news') }}</div>
         @endif
         
 



	         
              
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">All News</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>News Subject</th>
                        <th>Description</th>
                        <th>Status</th> 
                        <th>Added by</th>
                        <th>Created At</th>
                        <th>Actions</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($get_all_news as $news)
                      <tr>
                        <td>{{$news->main_subject}}</td>
                        <td>
                          {{$news->description}}
                          
                        </td>
                        
                          <td>
                            @if($news->active == 1)
                            Active
                            @else
                            Not Active
                            @endif
                          </td>
                        <td>
                        {{$news->AddedBy->name}}
                          
                      </td>
                        <td>
                          {{$news->created_at}}
                          </td>
                          
                    
                       
                    
                        <td>
                        	<a href="/last_news/{{$news->id}}" class="btn btn-info btn-md">View News</a>
                          <br>

                       
                  <a href="/delete_news/{{$news->id}}" class="btn btn-danger btn-md">Delete News</a>
                  <br>
                  @if($news->active == 0)
                  <a href="/active_news/{{$news->id}}" class="btn btn-md btn-success">Active News</a>
                  @elseif($news->active == 1)
                  <a href="/active_news/{{$news->id}}" class="btn btn-md btn-warning">Deactive News</a>
                  @endif
                        </td>
                        
                      </tr>
                      @endforeach 
                    </tbody>
                   
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
@include('back_end.footer')

public_html/resources/views/back_end/last_news/show.blade.php
@include('back_end.app')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            {{$get_one_news->main_subject}}

                
            
          </h1>
          <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
            
            <li class="active">News</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="col-xs-12">
          <div class="row">
             @if(session()->has('news_added'))
   <div class="alert alert-success">{{ session('news_added') }}</div>
         @endif

         @if(session()->has('success'))
   <div class="alert alert-success">{{ session('success') }}</div>
         @endif

         
      

        


          @if ($errors->any())
    <div class="alert alert-warning alert-dismissable">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <br>
@endif
          
 <div class="col-md-12">
              
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">News Information</h3>
                </div><!-- /.box-header -->
               
                  
                  <div class="box-body">
                    <div class="row">
                      <div class="col-md-12">
                      <form action="/update_news" method="post">
                        {{csrf_field()}}
                    <div class="col-md-6">
                      
                        <div class="form-group">
                        <label>Main Subject</label>
                        <input type="text" name="main_subject" class="form-control" value="{{$get_one_news->main_subject}}">
                    </div>
                    
              
</div>
<div class="col-md-6">
                      
                        <div class="form-group">
                         <label>News Description</label>
                   <textarea class="form-control" name="description" 
                    rows="5" cols="30" style="resize: none;">
                    {{$get_one_news->description}}
                   </textarea>
                    </div>
                    
              
</div>

<input type="submit" name="submit" value="Update News" class="btn btn-block btn-success btn-md">
<input type="hidden" name="news_id" value="{{$get_one_news->id}}">
</form>
</div>
                    </div>
                    
               
                  </div><!-- /.box-body -->

                 
                
              </div><!-- /.box -->

     <a href="/last_news" class="btn btn-primary btn-md btn-block">Back To All News</a>

           </div>
            </div><!-- /.col -->
          </div><!-- /.row -->
        
        </section><!-- /.content -->
      
      </div><!-- /.content-wrapper -->

     
@include('back_end.footer')